# docker compose up

services:
  postgres:
    image: postgres:17
    container_name: cashly_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cashly_db
      POSTGRES_USER: cashly_user
      POSTGRES_PASSWORD: cashly_password
    ports:
      - "5432:5432"
    volumes:
      - cashly_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cashly_api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://cashly_user:cashly_password@postgres:5432/cashly_db
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn backend.mainFastApi:app --host 0.0.0.0 --port 8001 --reload

volumes:
  cashly_postgres_data: