services:
  postgres:
    image: postgres:17
    container_name: cashly_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cashly_db
      POSTGRES_USER: cashly_user
      POSTGRES_PASSWORD: "123"

    ports:
      - "5433:5432"

    volumes:
      - cashly_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cashly_user -d cashly_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: backend/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://cashly_user:123@postgres:5432/cashly_db

    command: alembic upgrade head

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: cashly_api
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

    environment:
      DATABASE_URL: postgresql://cashly_user:123@postgres:5432/cashly_db

    ports:
      - "8001:8001"

volumes:
  cashly_postgres_data: